"""Migración inicial

Revision ID: 89558460d305
Revises: 
Create Date: 2023-10-19 18:26:05.375570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89558460d305'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AuthPermisos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('menu', sa.String(length=64), nullable=True),
    sa.Column('subMenu', sa.String(length=64), nullable=True),
    sa.Column('controlador', sa.String(length=64), nullable=True),
    sa.Column('metodoHTTP', sa.String(length=10), nullable=True),
    sa.Column('ruta', sa.String(length=256), nullable=True),
    sa.Column('descripcion', sa.String(length=256), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('menu'),
    sa.UniqueConstraint('subMenu')
    )
    op.create_table('AuthUsuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombreUsuario', sa.String(length=64), nullable=True),
    sa.Column('contrasenaHash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombreUsuario')
    )
    op.create_table('AuthUsuariosPermisos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuarioId', sa.Integer(), nullable=True),
    sa.Column('permisoId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['permisoId'], ['AuthPermisos.id'], ),
    sa.ForeignKeyConstraint(['usuarioId'], ['AuthUsuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('AuthUsuariosPermisos')
    op.drop_table('AuthUsuarios')
    op.drop_table('AuthPermisos')
    # ### end Alembic commands ###
