"""Migración Modifica campos en la tabla AuthPermisos

Revision ID: 9530220cf587
Revises: 89558460d305
Create Date: 2023-10-19 18:38:16.166826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9530220cf587'
down_revision = '89558460d305'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('AuthPermisos', schema=None) as batch_op:
        batch_op.drop_index('menu')
        batch_op.drop_index('subMenu')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('AuthPermisos', schema=None) as batch_op:
        batch_op.create_index('subMenu', ['subMenu'], unique=False)
        batch_op.create_index('menu', ['menu'], unique=False)

    # ### end Alembic commands ###
