"""Migración inicial

Revision ID: bab91e3812b9
Revises: 
Create Date: 2023-11-04 17:54:10.619430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bab91e3812b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AuthPermisos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('menu', sa.String(length=64), nullable=True),
    sa.Column('permissions', sa.String(length=64), nullable=True),
    sa.Column('controlador', sa.String(length=64), nullable=True),
    sa.Column('metodoHTTP', sa.String(length=10), nullable=True),
    sa.Column('ruta', sa.String(length=256), nullable=True),
    sa.Column('descripcion', sa.String(length=256), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('AuthUsuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombreUsuario', sa.String(length=64), nullable=True),
    sa.Column('contrasenaHash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombreUsuario')
    )
    op.create_table('AuthUsuariosPermisos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuarioId', sa.Integer(), nullable=True),
    sa.Column('permisoId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['permisoId'], ['AuthPermisos.id'], ),
    sa.ForeignKeyConstraint(['usuarioId'], ['AuthUsuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('AuthUsuariosPermisos')
    op.drop_table('AuthUsuarios')
    op.drop_table('AuthPermisos')
    # ### end Alembic commands ###
