"""Migración Modifica nombre del campo en la  tabla AuthPermisos

Revision ID: ea1c5f917b11
Revises: 9530220cf587
Create Date: 2023-10-19 19:21:24.471513

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ea1c5f917b11'
down_revision = '9530220cf587'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('AuthPermisos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permissions', sa.String(length=64), nullable=True))
        batch_op.drop_column('subMenu')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('AuthPermisos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subMenu', mysql.VARCHAR(length=64), nullable=True))
        batch_op.drop_column('permissions')

    # ### end Alembic commands ###
